### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by sha1sum** [mongodb-labs/elastic2-doc-manager#11]
The addition of AWS signing would warrant (in my opinion) a new release of the package, most likely 0.1.1, though that's obviously not my decision.

I can update the wiki to include instructions on adding AWS signing information to the JSON configuration, but do not think it would be wise to do so until #10 that @llvtt merged in becomes part of the latest released package.

**Comment by ShaneHarvey** [comment]
Thanks @sha1sum and @ReedD! We released version 0.2.0 which includes your AWS request signing enhancement. It would be great if you could update the [Usage with Elasticsearch wiki](https://github.com/mongodb-labs/mongo-connector/wiki/Usage%20with%20ElasticSearch#customizing-behavior-of-the-elastic-client) so others know about this feature. Thanks again, this release is largely you two.

**Comment by sha1sum** [comment]
@ShaneHarvey it seems that I cannot edit the wiki pages, but I've gladly typed out the Markdown for the bottom of the page if you'd like to simply paste it in:

```
### Signing Requests to AWS Elasticsearch Service

Both Elasticsearch 1.5.2 and 2.3 versions that&mdash;at the time of this writing&mdash;are provided by Amazon Elasticsearch Service through AWS are suported by [elastic-doc-manager](https://github.com/mongodb-labs/elastic-doc-manager) (for version 1.x) and [elastic2-doc-manager](https://github.com/mongodb-labs/elastic2-doc-manager) (for 2.x), respectively. The `args` for the proper doc manager in configuration file will accept an `aws` configuration object with a required `region` key and&mdash;optionally&mdash;an `access_id` and `secret_key` corresponding to your AWS credentials.

_**Note:**_ If `access_id` and `secret_key` are unspecified, the credentials found in the `~/.aws/credentials` file (if any) for the user running mongo-connector will be used instead, which may be the behavior that you want, particularly if you've already used [AWS CLI](https://aws.amazon.com/cli/).

#### Example AWS Usage

The following is an example of using AWS Elasticsearch service running Elasticsearch 1.5.2 using [elastic-doc-manager](https://github.com/mongodb-labs/elastic-doc-manager). The same `args` apply to both `elastic-doc-manager` and [`elastic2-doc-manager`](https://github.com/mongodb-labs/elastic2-doc-manager).

\```json
...
  "docManagers": [
    {
      "docManager": "elastic_doc_manager",
      "targetURL": "https://search-my-domain-29tg824978g24924t42.us-east-1.es.amazonaws.com/",
      "args": {
        "aws": {
        	"region": "us-east-1",
        	"access_id": "ACCESS_ID",
        	"secret_key": "SECRET_KEY"
        }
      }
    }
  ]
  ...
\```

As stated above, the `access_id` and `secret_key` arguments are optional if you are using credentials stored in `~/.aws/credentials` **for the user running** the `mongo-connector` instance.
```

Note that I had to "escape" the triple backticks to make this comment work with preformatted text :)

**Comment by ShaneHarvey** [comment]
Ah the wiki is only open to those with push access, sorry for the misinformation. I added your instructions to the wiki: https://github.com/mongodb-labs/mongo-connector/wiki/Usage-with-ElasticSearch#signing-requests-to-aws-elasticsearch-service. Thanks!
