### ISSUE TITLE
mongo-connector quits at start up when meeting bulkerror

### ISSUE THREAD

**Issue by arsenepark** [mongodb-labs/elastic2-doc-manager#20]
at mongo-connector starts up using ES bulk api, if some error occures(like "number_format_exception"), mongo-connector quits.

The following is an example:

BulkIndexError: (u'7 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'qwer', u'_id': u'57eb879f8d201115a9092ee7', u'error': {u'caused_by': {u'reason': u'For input string: "xyz"', u'type': u'number_format_exception'}, u'reason': u'failed to parse [abc]', u'type': u'mapper_parsing_exception'}, u'_index': u'4s'}}, {u'index': {u'status': 400, u'_type': u'qwer', u'_id': u'57eb87a68d201115a9092eee', u'error': {u'caused_by': {u'reason': u'For input string: "xyz"', u'type': u'number_format_exception'}, u'reason': u'failed to parse [abc]', u'type': u'mapper_parsing_exception'}, u'_index': u'4s'}}, {u'index': {u'status': 400, u'_type': u'qwer', u'_id': u'57eb87a68d201115a9092ef5', u'error': {u'caused_by': {u'reason': u'For input string: "xyz"', u'type': u'number_format_exception'}, u'reason': u'failed to parse [abc]', u'type': u'mapper_parsing_exception'}, u'_index': u'4s'}}, {u'index': {u'status': 400, u'_type': u'qwer', u'_id': u'57eb8d0e8b84d5f7f16c0641', u'error': {u'caused_by': {u'reason': u'For input string: "xyz"', u'type': u'number_format_exception'}, u'reason': u'failed to parse [abc]', u'type': u'mapper_parsing_exception'}, u'_index': u'4s'}}, {u'index': {u'status': 400, u'_type': u'qwer', u'_id': u'57eb8d2b8b84d5f7f16c0642', u'error': {u'caused_by': {u'reason': u'For input string: "xyz"', u'type': u'number_format_exception'}, u'reason': u'failed to parse [abc]', u'type': u'mapper_parsing_exception'}, u'_index': u'4s'}}, {u'index': {u'status': 400, u'_type': u'qwer', u'_id': u'57eb8d548b84d5f7f16c0643', u'error': {u'caused_by': {u'reason': u'For input string: "xyz"', u'type': u'number_format_exception'}, u'reason': u'failed to parse [abc]', u'type': u'mapper_parsing_exception'}, u'_index': u'4s'}}, {u'index': {u'status': 400, u'_type': u'qwer', u'_id': u'57eb8d5f8b84d5f7f16c0644', u'error': {u'caused_by': {u'reason': u'For input string: "xyz1"', u'type': u'number_format_exception'}, u'reason': u'failed to parse [abc]', u'type': u'mapper_parsing_exception'}, u'_index': u'4s'}}])
2016-09-28 17:32:31,034 [ERROR] mongo_connector.oplog_manager:638 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient(host=[u'10.163.183.190:28018', u'10.163.183.190:28017'], document_class=dict, tz_aware=False, connect=True, replicaset=u'repl4s'), u'local'), u'oplog.rs')

**Comment by arsenepark** [comment]
Here is a simple patch:

[elastic2_doc_manager.py.bulk.index.patch.zip](https://github.com/mongodb-labs/elastic2-doc-manager/files/497928/elastic2_doc_manager.py.bulk.index.patch.zip)

**Comment by bogdangi** [comment]
Any problems to go through bulk errors?

**Comment by ShaneHarvey** [comment]
I think you can use the [continueOnError](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration%20Options#continueonerror) option to work around this problem.

**Comment by ShaneHarvey** [comment]
See #26.
