### ISSUE TITLE
BulkIndexError and shutdown because of number_format_exception

### ISSUE THREAD

**Issue by villasv** [mongodb-labs/elastic2-doc-manager#26]
I just tried indexing a database on elasticsearch with `mongo-connector -m mongo:27017 -t elastic:9200 -d elastic2_doc_manager`

It just quits and i get this in the logfile:
`elasticsearch.helpers.BulkIndexError: ('18 document(s) failed to index.', [{'index': {'_type': 'item', 'status': 400, 'error': {'reason': 'failed to parse [start]', 'caused_by': {'reason': 'For input string: "2015-01-01T00:00:00"', 'type': 'number_format_exception'}, 'type': 'mapper_parsing_exception'}, '_id': '56e1c62112b16d31bad32a81', '_index': 'test'}}, ...`

I'm using ES5 and latest connector and manager from pip. Apparently all errors were related to dates, but those dates seem valid to me.

After installing from the master branch, I get this instead:
`elasticsearch.exceptions.TransportError: TransportError(N/A, 'Unable to sniff hosts - no viable hosts found.')`

**Comment by ShaneHarvey** [comment]
See #20 for working around this issue if you want mongo-connector to ignore this error.

My guess is that first a document was inserted with another datatype, eg integer `"date": 123`, then another document with a Date datatype, eg `"date":"2015-01-01T00:00:00"`.

Example:
```
$ curl -XPUT 'localhost:9200/test/item/1?pretty' -d'
{
    "date":123
}'

{
  "_index" : "test",
  "_type" : "item",
  "_id" : "1",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "created" : true
}
$ curl -XPUT 'localhost:9200/test/item/1?pretty' -d'
{
    "date":"2015-01-01T00:00:00"
}'

{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse [date]"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse [date]",
    "caused_by" : {
      "type" : "number_format_exception",
      "reason" : "For input string: \"2015-01-01T00:00:00\""
    }
  },
  "status" : 400
}
```
Check your mapping after running mongo-connector:
```
$ curl 'localhost:9200/test/_mapping/'
{"test":{"mappings":{"item":{"properties":{"date":{"type":"long"}}}}}}%
```

The fix would be to manually create your `test.item` mapping with the Date datatype before running mongo-connector: 
```
$ curl -XPUT 'localhost:9200/test?pretty' -d'
{
  "mappings": {
    "item": {
      "properties": {
        "date": {
          "type": "date"
        }
      }
    }
  }
}'
{
  "acknowledged" : true,
  "shards_acknowledged" : true
}
$ curl -XPUT 'localhost:9200/test/item/1?pretty' -d'
{
    "date":123
}'
{
  "_index" : "test",
  "_type" : "item",
  "_id" : "1",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "created" : true
}
$ curl -XPUT 'localhost:9200/test/item/1?pretty' -d'
{
    "date":"2015-01-01T00:00:00"
}'
{
  "_index" : "test",
  "_type" : "item",
  "_id" : "1",
  "_version" : 2,
  "result" : "updated",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "created" : false
}
```
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/date.html.

**Comment by villasv** [comment]
Closing, forgot to come back and say that @ShaneHarvey guess was right. Thanks ;-)
