### ISSUE TITLE
Service-Stop not handled gracefully

### ISSUE THREAD

**Issue by BlueRayONE** [mongodb-labs/elastic2-doc-manager#29]
[This is an outsource of an additional - a bit offtopic - discussion in #15.]
A small summary:

I had noticed, that not everything is synced properly. On every insert I had a "small" number of missing documents between mongoDB and ES, which is not synced. I observed differences between 70 and 900 documents. 
I could saw which documents where missing. When inserting new ones, the old ones - which were missing before - were synced then. That brought me to the idea, that maybe the last collection of new documents, which is collected for the next bulk-insert, is perhaps not transferred/committed properly to ES.
The solution delivered by @sliwinski-milosz was to activate [autoCommitInterval](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#docmanagersindexautocommitinterval).
Due to the changed config-file I had to restart the connector, but then, the documents which weren't committed at this point, where lost. I had to do a resync.
In @sliwinski-milosz opinion, this wasn't necessary when I would have gracefully stopped the connector. ("If you killed it, then of course you have to resync.")

The problem is solved, everything is as desired now, my documents are where they need to be. So there is no real issue anymore.
Only one (a bit trivial) question, which I want to mention when I already open a new issue: Was it really necessary to do the (work-intensive) resync? Or in other words: Worked the logic, which commits docs from bulk while stopping the connector, properly?
I installed the connector as a service, so I just restarted this service after making the changes in the config. So, firstly, I need to now, if this is a "gracefully stop"? Or how does he work, if not?

**Comment by sliwinski-milosz** [comment]
How did you do the restart? Was it: `sudo service mongo-connector restart`?

If yes.. resync should not be necessary. In that case, either there is a bug in stopping elastic2_doc_manager, or there is a bug in restarting service using above commend, which could not stop the service gracefully.

If you have stopped service other way, then that could not be the proper way :)

**Comment by BlueRayONE** [comment]
Yes, I did it with `sudo service mongo-connector restart`. 

So, it really seems to be a bug.
I took a look into the [service-script](https://github.com/mongodb-labs/mongo-connector/blob/master/scripts/mongo-connector#L58-L71). Can't find anything that looks like an intelligent logic that gives the doc-manager a chance to commit docs from the bulk.
You mean, that [this doc-manager-function](https://github.com/mongodb-labs/elastic2-doc-manager/blob/master/mongo_connector/doc_managers/elastic2_doc_manager.py#L142-L146) needs to be called when stopping, right?

**Comment by sliwinski-milosz** [comment]
nope... I think you are right. Mongo-connector catches only `KeyboardInterrupt` which catches Ctrl+C (and maybe SIGINT signal if they are the same).

In service-script it calls: `killproc` which sends SIGTERM signal, which is not handled. So it looks like mongo-connector needs to be updated to catch all signals (bug in mongo-connector).

I will take a closer look on that later and will send and update.

**Comment by BlueRayONE** [comment]
Okay, got it.

But changing the killproc param from `-9` to `-2` wouldn't be enough?! SIGINT needs to be handled from the connector, too.
I think with something like that needs to be in the [connector.py](https://github.com/mongodb-labs/mongo-connector/blob/master/mongo_connector/connector.py):
```
import signal

# the other code

def Exit_gracefully(signal, frame):
    dm.stop() #letting doc-manager commit remaining docs
    sys.exit(0)

if __name__ == '__main__':
    signal.signal(signal.SIGINT, Exit_gracefully)
    main()
```
([Source](http://stackoverflow.com/q/18114560/2831409))

I'm not that familar with python, but I could test it on my system tomorrow and put this small piece of code into a PR. But I can't write a corresponding test for this, there I need definitily help respectively somebody has to do this.

**Comment by ShaneHarvey** [comment]
The shell sends SIGINT to the foreground process on Ctrl+C so they are effectively the same; sending SIGINT to a Python process will cause KeyboardInterrupt to be raised. 

It is a bug that mongo-connector does not gracefully handle SIGTERM. This reminded me that there's already an issue for catching SIGTERM but https://github.com/mongodb-labs/mongo-connector/issues/461. Thanks for pointing this out, I'll make the signal changes to master this week.

**Comment by ShaneHarvey** [comment]
We should probably also increase the time that `killproc` waits until sending SIGKILL:
```
 -t<sec>
	      The  number <sec> specifies the seconds to wait between the sent signal SIGTERM and
	      the subsequentially signal SIGKILL if the first SIGTERM does not	show  any  result
	      within the first few milli seconds.  This defaults to 5 seconds.
```
http://www.unix.com/man-page/suse/8/killproc/

**Comment by ShaneHarvey** [comment]
Thanks @BlueRayONE and @sliwinski-milosz for your help debugging this issue.
