### ISSUE TITLE
does it work with elasticsearch 5.0.1 ?

### ISSUE THREAD

**Issue by DBARUNNER** [mongodb-labs/elastic2-doc-manager#30]
I have use elastic2_doc-manger with elasticsearch 2.0.2 now i upgrade my elasticsearch to 5.0.1 i afraid of it doesn't work, can any one answer me does it work or no ?

**Comment by ShaneHarvey** [comment]
For now, Elasticsearch 5.0.x is supported by following the instructions here: https://github.com/mongodb-labs/mongo-connector/issues/453#issuecomment-256103038.

**Comment by ShaneHarvey** [comment]
Elasticsearch 5.x support is included in the next release, see https://github.com/mongodb-labs/elastic2-doc-manager/pull/38
