### ISSUE TITLE
document update, excludeFields invalid

### ISSUE THREAD

**Issue by MrDreamWork** [mongodb-labs/elastic2-doc-manager#50]
I'm sorry.
ince my English sucks, machine translation can only be translated!

After synchronization is complete.
I update a document.

I find `excludeFields ` invalid!! 
The config file `excludeFields `, or `exclude_fields`.

My Config: 

> "exclude_fields": 
	[
	"value",
	"sourceValue",
	"sourceDataJobInfos.value",
	"sourceDataJobInfos.sourceValue"
	]

> 	"namespaces": {
		"nstlStorage.SOURCE_S02": {
			"excludeFields": ["value",
			"sourceValue",
			"sourceDataJobInfos.value",
			"sourceDataJobInfos.sourceValue"]
		}}

Concerns:   

> sourceDataJobInfos.value

**After updating**      There is this field `sourceDataJobInfos.value`
> {
	"_index": "nstlstorage",
	"_type": "SOURCE_S02",
	"_id": "04c9d2d77929833ebbeefe87ae58a532",
	"_version": 8,
	"found": true,
	"_source": {
		"sysId": "SS026276470",
		"localUpdateTime": "2017-06-30T08:04:35.340000+00:00",
		"_class": "com.ninemax.module.db.dao.storage.nosqldb.entity.SourceData",
		"status": "ADD",
		"sourceDataJobInfos": [{
			"citationNumber": 0,
			"storageJobId": 7898853,
			"filePath": "/data/nstldata/S/S02/2017-06-26/JIS_1706_2.xml",
			"dataType": "eng_standard_literature",
			"localCreateTime": "2017-06-30T08:04:35.340000+00:00",
			"value": """
				<paper xmlns="http: //www.nstl.gov.cn">
					<record_status>N</record_status>
					<identifier>6276470</identifier>
					<genuine_standard>false</genuine_standard>
					<unit_price>-1</unit_price>
				  </paper>
				""",
			"jobId": 3289,
			"sysXmlInfoId": 23,
			"operationType": "ADD",
			"dateStamp": "2017-06-25T16:00:00+00:00",
			"dataSourceCode": "3PL",
			"fileName": "JIS_1706_2.xml",
			"jobType": "FILEDATAJOBS",
			"fileId": "595327e4bd8c39dd474c7ae9"
		}],
		"subDocType": "S02",
		"dataType": "eng_standard_literature",
		"publishCount": 0,
		"sourceId": "6276470",
		"publishStatus": 1498924802306,
		"libraryCodes": ["CN111025"]
	}
}

**Before updating**  No this field

> {
	"_index": "nstlstorage",
	"_type": "SOURCE_S02",
	"_id": "04c9d2d77929833ebbeefe87ae58a532",
	"_version": 8,
	"found": true,
	"_source": {
		"sysId": "SS026276470",
		"localUpdateTime": "2017-06-30T08:04:35.340000+00:00",
		"_class": "com.ninemax.module.db.dao.storage.nosqldb.entity.SourceData",
		"status": "ADD",
		"sourceDataJobInfos": [{
			"citationNumber": 0,
			"storageJobId": 7898853,
			"filePath": "/data/nstldata/S/S02/2017-06-26/JIS_1706_2.xml",
			"dataType": "eng_standard_literature",
			"localCreateTime": "2017-06-30T08:04:35.340000+00:00",
			"jobId": 3289,
			"sysXmlInfoId": 23,
			"operationType": "ADD",
			"dateStamp": "2017-06-25T16:00:00+00:00",
			"dataSourceCode": "3PL",
			"fileName": "JIS_1706_2.xml",
			"jobType": "FILEDATAJOBS",
			"fileId": "595327e4bd8c39dd474c7ae9"
		}],
		"subDocType": "S02",
		"dataType": "eng_standard_literature",
		"publishCount": 0,
		"sourceId": "6276470",
		"publishStatus": 1498924802306,
		"libraryCodes": ["CN111025"]
	}
}

**Comment by ShaneHarvey** [comment]
This limitation on excludeFields is pointed out in the documentation:
> Note: mongo-connector does not support filtering fields inside arrays, you can only include or exclude the entire array field.

https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#filtering-documents-per-namespace

**Comment by MrDreamWork** [comment]
Thank you for answering my question
But,This setting is good when you import data for the first time

I'm really surprised
