### ISSUE TITLE
如何配置过滤条件只同步集合部分数据

### ISSUE THREAD

**Issue by xkissboss** [mongodb-labs/elastic2-doc-manager#54]
如何配置过滤条件只同步集合部分数据

**Comment by ShaneHarvey** [comment]
See: https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#including-namespaces

And: https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#filtering-documents-per-namespace
