### ISSUE TITLE
BulkIndexError needs to be caught in bulk_upsert

### ISSUE THREAD

**Issue by llvtt** [mongodb-labs/elastic2-doc-manager#6]
See https://github.com/mongodb-labs/mongo-connector/issues/482 for details.

**Comment by estobbart** [comment]
I'd like to fix this one, I'm also hitting it. How do you propose it be resolved? Easy way, is catch/log/keep running? Feels to me like there needs to be a failed to index log, that maybe can be applied manually.

**Comment by estobbart** [comment]
The easy way would be.. lines 195:201

            kw = {'raise_on_error': False}
            if self.chunk_size > 0:
                kw['chunk_size'] = self.chunk_size

            responses = streaming_bulk(client=self.elastic,
                                       actions=docs_to_upsert(),
                                       **kw)

**Comment by llvtt** [comment]
If you'd like to fix it, go ahead! I appreciate the effort. You could also do two-for-one by making basically the same pull request for this issue here: https://github.com/mongodb-labs/elastic-doc-manager/issues/1

I recommend just mapping `BulkIndexError` to `OperationFailed` here: https://github.com/mongodb-labs/elastic2-doc-manager/blob/master/mongo_connector/doc_managers/elastic2_doc_manager.py#L39-L43. This will cause the Exception to be re-raised as `OperationFailed`, which will be caught in mongo-connector's OplogThread and logged. The OplogThread will continue to run after this happens.
